# -*- coding: utf-8 -*-
"""aadhar-enrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KthgTnrxmQV42LRHZtuSoBBVY0u5a3d7
"""



"""**Reasoning**:
Now, as per the subtask instruction to generate heatmaps, I will create a heatmap to visualize the total enrolment distribution by 'state' and 'month'. This will help in understanding seasonal patterns across different states.
"""

heatmap_data = combined_df.groupby(['state', 'month'])['total_enrolment'].sum().unstack(fill_value=0)

plt.figure(figsize=(15, 10))
sns.heatmap(heatmap_data, cmap='viridis', annot=False, fmt='g', linewidths=.5)
plt.title('Total Enrolment by State and Month (Heatmap)')
plt.xlabel('Month')
plt.ylabel('State')
plt.tight_layout()
plt.show()

"""# Task
Perform a comprehensive analysis of Aadhar enrolment data by loading and consolidating all provided CSV files, including "api_data_aadhar_enrolment_1000000_1006029.csv", "api_data_aadhar_enrolment_0_500000.csv", and "api_data_aadhar_enrolment_500000_1000000.csv", into a single pandas DataFrame. The analysis will involve data cleaning, geographic standardization, feature engineering, exploratory data analysis, advanced interactive visualizations, statistical and anomaly analysis, machine learning for anomaly detection and forecasting, and clustering regions by enrolment behavior. Finally, generate policy-ready insights and summarize the entire analysis with all outputs and key findings.

## Load and Consolidate Data

### Subtask:
Load all provided Aadhar enrolment CSV files into a single pandas DataFrame for initial processing.

**Reasoning**:
To begin, I'll import the pandas library, load each specified CSV file into individual DataFrames, and then consolidate them into a single DataFrame. Finally, I'll display the head and info of the combined DataFrame to ensure correct loading and structure.
"""

import pandas as pd

# List of CSV files to load
csv_files = [
    '/content/api_data_aadhar_enrolment_0_500000.csv',
    '/content/api_data_aadhar_enrolment_500000_1000000.csv',
    '/content/api_data_aadhar_enrolment_1000000_1006029.csv'
]

# Load each CSV file into a DataFrame and store them in a list
dfs = []
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

# Display the first few rows of the consolidated DataFrame
print("First 5 rows of the combined DataFrame:")
print(combined_df.head())

# Display information about the consolidated DataFrame (column names, data types, non-null counts)
print("\nInformation about the combined DataFrame:")
combined_df.info()

"""## Data Cleaning and Initial Validation

### Subtask:
Convert date columns to datetime objects, handle missing values, ensure non-negative counts for relevant metrics, and compute the 'total_enrolment' column. Provide plots to visualize the distribution of 'total_enrolment' before and after cleaning.

**Reasoning**:
The first step is to convert the 'date' column to datetime objects to enable time-series analysis and then check for and handle any potential missing values, although based on the info, there are none, it's good practice to confirm. Next, I will verify and correct any non-positive counts in the age group columns, as enrollment numbers must be non-negative. Finally, I will compute the 'total_enrolment' column by summing the age group columns, which is essential for further analysis.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Convert 'date' column to datetime objects
# The format seems to be 'DD-MM-YYYY'
combined_df['date'] = pd.to_datetime(combined_df['date'], format='%d-%m-%Y')
print("Date column converted to datetime:")
print(combined_df['date'].head())

# 2. Check for and handle missing values
missing_values = combined_df.isnull().sum()
print("\nMissing values before handling:")
print(missing_values[missing_values > 0])

# Given the previous info() output, there should be no missing values.
# If there were, a common strategy would be to drop rows or impute,
# but for this dataset, it's likely not needed.

# 3. Verify non-negative counts for age columns
age_columns = ['age_0_5', 'age_5_17', 'age_18_greater']

# Check for negative values
negative_counts = combined_df[age_columns][combined_df[age_columns] < 0].sum()
print("\nNegative counts in age columns (should be 0 if none):")
print(negative_counts)

# If negative values were present, a common approach for count data is to replace with 0.
# For this dataset, assuming counts should never be negative.
for col in age_columns:
    if (combined_df[col] < 0).any():
        print(f"Correcting negative values in column: {col}")
        combined_df[col] = combined_df[col].apply(lambda x: max(0, x))

# 4. Create 'total_enrolment' column
combined_df['total_enrolment'] = combined_df['age_0_5'] + combined_df['age_5_17'] + combined_df['age_18_greater']

print("\n'total_enrolment' column created. First 5 rows:")
print(combined_df[['age_0_5', 'age_5_17', 'age_18_greater', 'total_enrolment']].head())

# Display descriptive statistics for 'total_enrolment'
print("\nDescriptive statistics for 'total_enrolment' before visualization:")
print(combined_df['total_enrolment'].describe())

"""**Reasoning**:
Now that the 'total_enrolment' column has been created and the data cleaning steps have been performed, I will generate a histogram to visualize its distribution. This will help in understanding the spread and identifying any potential outliers as per the subtask instructions.


"""

plt.figure(figsize=(10, 6))
sns.histplot(combined_df['total_enrolment'], bins=50, kde=True)
plt.title('Distribution of Total Enrolment After Cleaning')
plt.xlabel('Total Enrolment')
plt.ylabel('Frequency')
plt.show()

"""## Geographic Standardization and Deduplication

### Subtask:
Standardize geographic fields (e.g., State, District, Pincode) to ensure consistency, and identify and remove duplicate records from the dataset. Visualize the count of unique geographic entities before and after standardization.

**Reasoning**:
I will start by preparing the 'state' and 'district' columns for standardization by storing their initial unique counts and then converting them to lowercase and stripping whitespace. This will ensure consistency in the geographic data before further analysis.
"""

print("Unique counts before standardization:")

unique_states_before = combined_df['state'].nunique()
unique_districts_before = combined_df['district'].nunique()
unique_pincodes_before = combined_df['pincode'].nunique()

print(f"  Unique states: {unique_states_before}")
print(f"  Unique districts: {unique_districts_before}")
print(f"  Unique pincodes: {unique_pincodes_before}")

# 1. Convert 'state' and 'district' columns to lowercase and strip whitespace
combined_df['state'] = combined_df['state'].str.lower().str.strip()
combined_df['district'] = combined_df['district'].str.lower().str.strip()

print("\nGeographic fields 'state' and 'district' standardized to lowercase and stripped of whitespace.")

# 2. Calculate and print the number of unique values after standardization
print("\nUnique counts after standardization:")

unique_states_after = combined_df['state'].nunique()
unique_districts_after = combined_df['district'].nunique()
# Pincode does not undergo standardization in this step, so its count remains the same.
unique_pincodes_after = combined_df['pincode'].nunique()

print(f"  Unique states: {unique_states_after}")
print(f"  Unique districts: {unique_districts_after}")
print(f"  Unique pincodes: {unique_pincodes_after}")

# Store these values for plotting
unique_counts_data = {
    'entity': ['state_before', 'state_after', 'district_before', 'district_after'],
    'count': [unique_states_before, unique_states_after, unique_districts_before, unique_districts_after]
}
unique_counts_df = pd.DataFrame(unique_counts_data)

# 3. Identify and remove duplicate rows
rows_before_deduplication = combined_df.shape[0]
combined_df.drop_duplicates(inplace=True)
rows_after_deduplication = combined_df.shape[0]

# 4. Print the number of rows before and after deduplication
print(f"\nNumber of rows before deduplication: {rows_before_deduplication}")
print(f"Number of rows after deduplication: {rows_after_deduplication}")
print(f"Number of duplicate rows removed: {rows_before_deduplication - rows_after_deduplication}")

"""**Reasoning**:
Now that the unique counts for states and districts before and after standardization have been computed and stored in `unique_counts_df`, I will create a bar chart to visualize these changes as requested by the subtask.


"""

plt.figure(figsize=(10, 6))
sns.barplot(x='entity', y='count', data=unique_counts_df, palette='viridis')
plt.title('Unique Geographic Entities Before and After Standardization')
plt.xlabel('Entity Type')
plt.ylabel('Count of Unique Entities')
plt.xticks(ticks=[0, 1, 2, 3], labels=['State Before', 'State After', 'District Before', 'District After'], rotation=45)
plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous code produced a `FutureWarning` because `palette` was used without `hue`. To fix this, I will assign the `x` variable to `hue` and set `legend=False` in the `sns.barplot` function, as suggested by the warning.


"""

plt.figure(figsize=(10, 6))
sns.barplot(x='entity', y='count', data=unique_counts_df, hue='entity', palette='viridis', legend=False)
plt.title('Unique Geographic Entities Before and After Standardization')
plt.xlabel('Entity Type')
plt.ylabel('Count of Unique Entities')
plt.xticks(ticks=[0, 1, 2, 3], labels=['State Before', 'State After', 'District Before', 'District After'], rotation=45)
plt.tight_layout()
plt.show()

"""## Temporal Feature Engineering

### Subtask:
Create new temporal features such as year, month, week, weekday, and quarter from the date columns to capture seasonal and periodic patterns. Provide plots of enrolment trends by these new temporal features.

**Reasoning**:
I will create new temporal features (year, month, week, weekday, and quarter) from the 'date' column in `combined_df` to prepare for analyzing seasonal and periodic patterns in enrolment.
"""

combined_df['year'] = combined_df['date'].dt.year
combined_df['month'] = combined_df['date'].dt.month
combined_df['week'] = combined_df['date'].dt.isocalendar().week.astype(int)
combined_df['weekday'] = combined_df['date'].dt.dayofweek # Monday=0, Sunday=6
combined_df['quarter'] = combined_df['date'].dt.quarter

print("New temporal features added to combined_df. Head of relevant columns:")
print(combined_df[['date', 'year', 'month', 'week', 'weekday', 'quarter', 'total_enrolment']].head())

"""**Reasoning**:
Now that the temporal features have been created, I will aggregate the 'total_enrolment' by each new temporal feature (year, month, week, weekday, quarter) and then generate the requested plots to visualize the trends.


"""

temporal_features = ['year', 'month', 'week', 'weekday', 'quarter']

for feature in temporal_features:
    # Group by the temporal feature and sum 'total_enrolment'
    enrolment_by_feature = combined_df.groupby(feature)['total_enrolment'].sum().reset_index()

    plt.figure(figsize=(12, 6))
    if feature == 'year':
        sns.lineplot(x=feature, y='total_enrolment', data=enrolment_by_feature)
    else:
        sns.barplot(x=feature, y='total_enrolment', data=enrolment_by_feature, palette='viridis')

    plt.title(f'Total Enrolment Trend by {feature.replace("_", " ").title()}')
    plt.xlabel(feature.replace("_", " ").title())
    plt.ylabel('Total Enrolment')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""**Reasoning**:
The previous code produced `FutureWarning` messages due to the incorrect use of `palette` in `sns.barplot` without `hue`. I will fix this by assigning the `x` variable to `hue` and setting `legend=False` in the `sns.barplot` calls, as suggested by the warning.


"""

temporal_features = ['year', 'month', 'week', 'weekday', 'quarter']

for feature in temporal_features:
    # Group by the temporal feature and sum 'total_enrolment'
    enrolment_by_feature = combined_df.groupby(feature)['total_enrolment'].sum().reset_index()

    plt.figure(figsize=(12, 6))
    if feature == 'year':
        sns.lineplot(x=feature, y='total_enrolment', data=enrolment_by_feature)
    else:
        # Fix: Assign 'x' to 'hue' and set 'legend=False' to resolve FutureWarning
        sns.barplot(x=feature, y='total_enrolment', data=enrolment_by_feature, hue=feature, palette='viridis', legend=False)

    plt.title(f'Total Enrolment Trend by {feature.replace("_", " ").title()}')
    plt.xlabel(feature.replace("_", " ").title())
    plt.ylabel('Total Enrolment')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""## Demographic Ratios and Rolling Statistics

### Subtask:
Compute demographic ratios and dependency indicators (if relevant demographic data is available). Calculate rolling statistics (7-day and 30-day mean, standard deviation, and growth rates) for key enrolment metrics. Visualize these rolling trends over time.

**Reasoning**:
I will start by calculating the demographic ratios for each age group by dividing their respective enrolment counts by the `total_enrolment`. Then, I will sort the DataFrame by date, calculate various rolling statistics (7-day and 30-day means and standard deviations for total enrolment, and daily growth rates with their rolling means), and print the head of the DataFrame to show these newly computed columns.
"""

import numpy as np

# 1. Calculate demographic ratios
combined_df['age_0_5_ratio'] = combined_df['age_0_5'] / combined_df['total_enrolment']
combined_df['age_5_17_ratio'] = combined_df['age_5_17'] / combined_df['total_enrolment']
combined_df['age_18_greater_ratio'] = combined_df['age_18_greater'] / combined_df['total_enrolment']

# Handle potential division by zero resulting in NaN or Inf for ratios where total_enrolment might be 0
# For Aadhar enrolment, total_enrolment is min 1, so this might not be strictly necessary, but good practice.
combined_df.replace([np.inf, -np.inf], np.nan, inplace=True)
combined_df.fillna(0, inplace=True) # Replace NaN ratios with 0 if total_enrolment was 0

# 2. Sort the DataFrame by 'date'
combined_df = combined_df.sort_values(by='date').reset_index(drop=True)

# 3. Calculate 7-day rolling mean and standard deviation of 'total_enrolment'
combined_df['rolling_mean_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
combined_df['rolling_std_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=7, min_periods=1).std())

# 4. Calculate 30-day rolling mean and standard deviation of 'total_enrolment'
combined_df['rolling_mean_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())
combined_df['rolling_std_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=30, min_periods=1).std())

# 5. Calculate daily growth rate of 'total_enrolment'
# To calculate growth rate correctly, we need the previous day's enrolment for the same location.
# We will use shift(1) after grouping by location.
combined_df['previous_enrolment'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].shift(1)
combined_df['daily_growth_rate'] = (combined_df['total_enrolment'] - combined_df['previous_enrolment']) / combined_df['previous_enrolment']

# Handle potential division by zero (inf) and NaN values for daily_growth_rate
combined_df.replace([np.inf, -np.inf], np.nan, inplace=True)
# For the first entry or where previous_enrolment was 0, growth rate can be NaN. Fill with 0 or a suitable value.
combined_df['daily_growth_rate'].fillna(0, inplace=True)

# 6. Calculate 7-day and 30-day rolling mean of 'daily_growth_rate'
combined_df['rolling_growth_rate_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['daily_growth_rate'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
combined_df['rolling_growth_rate_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['daily_growth_rate'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())

# Drop the temporary 'previous_enrolment' column
combined_df.drop(columns=['previous_enrolment'], inplace=True)

# 7. Print the head of the DataFrame with new columns
print("Combined DataFrame with new demographic ratios and rolling statistics:")
print(combined_df.head())

"""**Reasoning**:
The previous code generated a `FutureWarning` about `inplace=True` with chained assignment. I will correct this to ensure better compatibility with future pandas versions. Then, I will aggregate the calculated rolling statistics by date to visualize the overall trends as requested by the subtask instructions, creating line plots for both total enrolment and daily growth rate rolling means.


"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Calculate demographic ratios
combined_df['age_0_5_ratio'] = combined_df['age_0_5'] / combined_df['total_enrolment']
combined_df['age_5_17_ratio'] = combined_df['age_5_17'] / combined_df['total_enrolment']
combined_df['age_18_greater_ratio'] = combined_df['age_18_greater'] / combined_df['total_enrolment']

# Handle potential division by zero resulting in NaN or Inf for ratios where total_enrolment might be 0
# For Aadhar enrolment, total_enrolment is min 1, so this might not be strictly necessary, but good practice.
combined_df.replace([np.inf, -np.inf], np.nan, inplace=True)
combined_df.fillna(0, inplace=True) # Replace NaN ratios with 0 if total_enrolment was 0

# 2. Sort the DataFrame by 'date'
combined_df = combined_df.sort_values(by='date').reset_index(drop=True)

# 3. Calculate 7-day rolling mean and standard deviation of 'total_enrolment'
combined_df['rolling_mean_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
combined_df['rolling_std_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=7, min_periods=1).std())

# 4. Calculate 30-day rolling mean and standard deviation of 'total_enrolment'
combined_df['rolling_mean_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())
combined_df['rolling_std_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].transform(lambda x: x.rolling(window=30, min_periods=1).std())

# 5. Calculate daily growth rate of 'total_enrolment'
# To calculate growth rate correctly, we need the previous day's enrolment for the same location.
# We will use shift(1) after grouping by location.
combined_df['previous_enrolment'] = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].shift(1)
combined_df['daily_growth_rate'] = (combined_df['total_enrolment'] - combined_df['previous_enrolment']) / combined_df['previous_enrolment']

# Handle potential division by zero (inf) and NaN values for daily_growth_rate
combined_df.replace([np.inf, -np.inf], np.nan, inplace=True)
# Fix: Assign back to the column to avoid `FutureWarning` for `inplace=True` with chained assignment
combined_df['daily_growth_rate'] = combined_df['daily_growth_rate'].fillna(0)

# 6. Calculate 7-day and 30-day rolling mean of 'daily_growth_rate'
combined_df['rolling_growth_rate_7d'] = combined_df.groupby(['state', 'district', 'pincode'])['daily_growth_rate'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())
combined_df['rolling_growth_rate_30d'] = combined_df.groupby(['state', 'district', 'pincode'])['daily_growth_rate'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())

# Drop the temporary 'previous_enrolment' column
combined_df.drop(columns=['previous_enrolment'], inplace=True)

# 7. Print the head of the DataFrame with new columns
print("Combined DataFrame with new demographic ratios and rolling statistics:")
print(combined_df.head())

# Aggregate rolling statistics by date for visualization of overall trends
# Using mean for aggregation to represent the overall trend across locations for each date
daily_trends_df = combined_df.groupby('date').agg({
    'rolling_mean_7d': 'mean',
    'rolling_mean_30d': 'mean',
    'rolling_growth_rate_7d': 'mean',
    'rolling_growth_rate_30d': 'mean'
}).reset_index()

# 8. Create line plots for 7-day and 30-day rolling means of 'total_enrolment'
plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='rolling_mean_7d', data=daily_trends_df, label='7-day Rolling Mean')
sns.lineplot(x='date', y='rolling_mean_30d', data=daily_trends_df, label='30-day Rolling Mean')
plt.title('Overall Total Enrolment Rolling Means Over Time')
plt.xlabel('Date')
plt.ylabel('Average Total Enrolment')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# 9. Create line plots for 7-day and 30-day rolling means of 'daily_growth_rate'
plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='rolling_growth_rate_7d', data=daily_trends_df, label='7-day Rolling Mean Growth Rate')
sns.lineplot(x='date', y='rolling_growth_rate_30d', data=daily_trends_df, label='30-day Rolling Mean Growth Rate')
plt.title('Overall Daily Enrolment Growth Rate Rolling Means Over Time')
plt.xlabel('Date')
plt.ylabel('Average Daily Growth Rate')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Geographic Aggregations

### Subtask:
Aggregate the enrolment data at national, state, district, and pincode levels to understand hierarchical contributions and identify top-performing or underperforming regions. Provide bar charts or tables summarizing these aggregations.

**Reasoning**:
I will aggregate the total enrolment at the national, state, and district levels, and then display the total national enrolment and a table of the top 10 states by enrolment as the first part of the geographic aggregations.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Aggregate the total_enrolment at national, state, district, and pincode levels
# National enrolment
national_enrolment = combined_df['total_enrolment'].sum()

# State-level aggregation
state_enrolment_df = combined_df.groupby('state')['total_enrolment'].sum().reset_index()
state_enrolment_df = state_enrolment_df.sort_values(by='total_enrolment', ascending=False)

# District-level aggregation
district_enrolment_df = combined_df.groupby(['state', 'district'])['total_enrolment'].sum().reset_index()
district_enrolment_df = district_enrolment_df.sort_values(by='total_enrolment', ascending=False)

# Pincode-level aggregation (not explicitly requested for display, but good to have for later)
pincode_enrolment_df = combined_df.groupby(['state', 'district', 'pincode'])['total_enrolment'].sum().reset_index()
pincode_enrolment_df = pincode_enrolment_df.sort_values(by='total_enrolment', ascending=False)

# 2. Print the total national enrolment
print(f"Total National Enrolment: {national_enrolment:,}")

# 3. Display the top 10 states by total_enrolment in a table
print("\nTop 10 States by Total Enrolment:")
print(state_enrolment_df.head(10).to_markdown(index=False))

"""**Reasoning**:
Now that the top 10 states by total enrolment have been identified, I will generate a bar chart to visualize their total enrolments, as specified by the subtask instructions.


"""

plt.figure(figsize=(12, 7))
sns.barplot(x='state', y='total_enrolment', data=state_enrolment_df.head(10), palette='viridis')
plt.title('Top 10 States by Total Enrolment')
plt.xlabel('State')
plt.ylabel('Total Enrolment')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous code generated a `FutureWarning` due to the incorrect use of `palette` without `hue` in `sns.barplot`. I will fix this by assigning the `x` variable ('state') to `hue` and setting `legend=False`, as suggested by the warning. Additionally, I will add the next steps as per the subtask instructions, which include displaying the top 10 districts by total enrolment in a table and generating a bar chart for them.


"""

plt.figure(figsize=(12, 7))
sns.barplot(x='state', y='total_enrolment', data=state_enrolment_df.head(10), hue='state', palette='viridis', legend=False)
plt.title('Top 10 States by Total Enrolment')
plt.xlabel('State')
plt.ylabel('Total Enrolment')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 5. Display the top 10 districts by total_enrolment in a table
print("\nTop 10 Districts by Total Enrolment:")
print(district_enrolment_df.head(10).to_markdown(index=False))

# 6. Create a bar chart showing the total enrolment for the top 10 districts.
plt.figure(figsize=(12, 7))
sns.barplot(x='district', y='total_enrolment', data=district_enrolment_df.head(10), hue='district', palette='viridis', legend=False)
plt.title('Top 10 Districts by Total Enrolment')
plt.xlabel('District')
plt.ylabel('Total Enrolment')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Exploratory Data Analysis and Visualization

### Subtask:
Perform comprehensive EDA to identify national, state, and district trends. Analyze demographic distribution shifts over time and conduct seasonal and regional comparisons. Generate time-series plots, rolling trend plots, and comparative bar charts with legends.

**Reasoning**:
I will aggregate the `total_enrolment` by `date` to get the national daily enrolment trend and then create a line plot to visualize this national trend over time, as per the first instruction.
"""

national_daily_enrolment = combined_df.groupby('date')['total_enrolment'].sum().reset_index()

plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='total_enrolment', data=national_daily_enrolment)
plt.title('National Daily Enrolment Trend Over Time')
plt.xlabel('Date')
plt.ylabel('Total Enrolment')
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Reasoning**:
I will calculate the average demographic ratios grouped by date and then plot these average ratios over time using line plots to identify shifts in demographic distribution, as per the second instruction.


"""

demographic_ratios_by_date = combined_df.groupby('date')[['age_0_5_ratio', 'age_5_17_ratio', 'age_18_greater_ratio']].mean().reset_index()

plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='age_0_5_ratio', data=demographic_ratios_by_date, label='Age 0-5 Ratio')
sns.lineplot(x='date', y='age_5_17_ratio', data=demographic_ratios_by_date, label='Age 5-17 Ratio')
sns.lineplot(x='date', y='age_18_greater_ratio', data=demographic_ratios_by_date, label='Age 18+ Ratio')
plt.title('Average Demographic Ratios Over Time')
plt.xlabel('Date')
plt.ylabel('Average Ratio')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""**Reasoning**:
I will identify the top 5 states and top 5 districts based on total enrolment from the pre-computed `state_enrolment_df` and `district_enrolment_df` DataFrames, as per the third instruction of the subtask.


"""

top_5_states = state_enrolment_df.head(5)['state'].tolist()
top_5_districts = district_enrolment_df.head(5)['district'].tolist()

print(f"Top 5 States by Total Enrolment: {top_5_states}")
print(f"Top 5 Districts by Total Enrolment: {top_5_districts}")

"""**Reasoning**:
I will filter the `combined_df` for the `top_5_states`, then aggregate the `total_enrolment` by `date` and `state` for these states. Finally, I will generate separate line plots for each of the top 5 states to visualize their individual enrolment trends over time, as per instruction 4.


"""

for state in top_5_states:
    state_enrolment_trend = combined_df[combined_df['state'] == state].groupby('date')['total_enrolment'].sum().reset_index()

    plt.figure(figsize=(14, 7))
    sns.lineplot(x='date', y='total_enrolment', data=state_enrolment_trend)
    plt.title(f'Total Enrolment Trend Over Time in {state.title()}')
    plt.xlabel('Date')
    plt.ylabel('Total Enrolment')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

"""**Reasoning**:
I will now iterate through the `top_5_districts`, filter the `combined_df` for each district, aggregate the `total_enrolment` by `date`, and generate separate line plots to visualize their individual enrolment trends over time, as per instruction 5.


"""

for district in top_5_districts:
    district_enrolment_trend = combined_df[combined_df['district'] == district].groupby('date')['total_enrolment'].sum().reset_index()

    plt.figure(figsize=(14, 7))
    sns.lineplot(x='date', y='total_enrolment', data=district_enrolment_trend)
    plt.title(f'Total Enrolment Trend Over Time in {district.title()} District')
    plt.xlabel('Date')
    plt.ylabel('Total Enrolment')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

"""**Reasoning**:
I will aggregate the average demographic ratios by state for the top 10 states and then create a comparative bar chart to visualize these ratios, as per instruction 6.


"""

top_10_states = state_enrolment_df.head(10)['state'].tolist()

demographic_ratios_by_top_states = combined_df[combined_df['state'].isin(top_10_states)].groupby('state')[['age_0_5_ratio', 'age_5_17_ratio', 'age_18_greater_ratio']].mean().reset_index()

demographic_ratios_by_top_states_melted = demographic_ratios_by_top_states.melt(id_vars='state', var_name='Age Group', value_name='Average Ratio')

plt.figure(figsize=(16, 8))
sns.barplot(x='state', y='Average Ratio', hue='Age Group', data=demographic_ratios_by_top_states_melted, palette='viridis')
plt.title('Average Demographic Ratios for Top 10 States')
plt.xlabel('State')
plt.ylabel('Average Ratio')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Age Group')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""**Reasoning**:
I will aggregate the average demographic ratios by district for the top 10 districts and then create a comparative bar chart to visualize these ratios, as per instruction 7 of the subtask.


"""

top_10_districts = district_enrolment_df.head(10)['district'].tolist()

demographic_ratios_by_top_districts = combined_df[combined_df['district'].isin(top_10_districts)].groupby('district')[['age_0_5_ratio', 'age_5_17_ratio', 'age_18_greater_ratio']].mean().reset_index()

demographic_ratios_by_top_districts_melted = demographic_ratios_by_top_districts.melt(id_vars='district', var_name='Age Group', value_name='Average Ratio')

plt.figure(figsize=(16, 8))
sns.barplot(x='district', y='Average Ratio', hue='Age Group', data=demographic_ratios_by_top_districts_melted, palette='viridis')
plt.title('Average Demographic Ratios for Top 10 Districts')
plt.xlabel('District')
plt.ylabel('Average Ratio')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Age Group')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""## Advanced Interactive Visualizations

### Subtask:
Create interactive Plotly sunburst charts to visualize the hierarchical distribution of enrolments (India → State → District → Pincode). Generate treemaps and heatmaps to highlight significant patterns and deviations.

**Reasoning**:
I will import the `plotly.express` module as `px` to enable the creation of interactive visualizations for the subtask.
"""

import plotly.express as px

print("Plotly Express imported successfully.")

"""**Reasoning**:
I will prepare the data for the sunburst chart by adding a 'country' level, aggregating enrolment hierarchically, and then using `px.sunburst` to visualize the distribution from country down to pincode, as specified in the instructions.


"""

hierarchical_df = combined_df.copy()
hierarchical_df['country'] = 'India'

# Aggregate total_enrolment at the country, state, district, and pincode levels
sunburst_data = hierarchical_df.groupby(['country', 'state', 'district', 'pincode'])['total_enrolment'].sum().reset_index()

# Create the sunburst chart
fig_sunburst = px.sunburst(sunburst_data,
                           path=['country', 'state', 'district', 'pincode'],
                           values='total_enrolment',
                           title='Hierarchical Distribution of Total Enrolment',
                           color_continuous_scale='Viridis')

fig_sunburst.show()

"""**Reasoning**:
Now, as per the third instruction, I will create a treemap to visualize the total enrolment distribution by 'state' and 'district' by aggregating the `total_enrolment` at these levels and then using `px.treemap`.


"""

treemap_data = combined_df.groupby(['state', 'district'])['total_enrolment'].sum().reset_index()

fig_treemap = px.treemap(treemap_data,
                           path=['state', 'district'],
                           values='total_enrolment',
                           title='Total Enrolment Distribution by State and District',
                           color_continuous_scale='Plasma')

fig_treemap.show()