# -*- coding: utf-8 -*-
"""empathy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCqaYRndErMKi2EAREMFDc2aYS63R6-H
"""

"""
Therapy Response Dataset Cleaner and Trainer
============================================
This script cleans a therapy response dataset and trains a DistilBERT model
for intent classification in a mental health chatbot context.

Author: James Avila
Date: 2024
"""

import json
import torch
import os
import re
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import warnings

# Disable wandb and unnecessary warnings
os.environ["WANDB_DISABLED"] = "true"
warnings.filterwarnings("ignore", message="Some weights of DistilBertForSequenceClassification")


# =============================
# DATA CLEANING FUNCTIONS
# =============================

def clean_text(text):
    """
    Clean text by removing extra whitespace, special characters, and normalizing.

    Args:
        text (str): Raw text to clean

    Returns:
        str: Cleaned text
    """
    if not text or not isinstance(text, str):
        return ""

    # Remove extra whitespace and newlines
    text = re.sub(r'\s+', ' ', text)

    # Remove leading/trailing whitespace
    text = text.strip()

    # Remove special unicode characters that might cause issues
    text = text.encode('ascii', 'ignore').decode('ascii')

    # Normalize quotes
    text = text.replace('\u2019', "'").replace('\u201c', '"').replace('\u201d', '"')

    return text


def load_and_clean_therapy_data(file_path):
    """
    Load therapy dataset from JSONL format and clean it.

    Expected format: Each line is a JSON object with "Context" and "Response" keys

    Args:
        file_path (str): Path to the therapy dataset file

    Returns:
        tuple: (contexts, responses) - lists of cleaned contexts and responses
    """
    contexts = []
    responses = []

    print(f"📂 Loading data from {file_path}...")

    with open(file_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            try:
                # Parse JSON line
                data = json.loads(line.strip())

                # Extract context and response
                context = data.get('Context', '')
                response = data.get('Response', '')

                # Clean the texts
                context = clean_text(context)
                response = clean_text(response)

                # Skip if either is empty
                if context and response:
                    contexts.append(context)
                    responses.append(response)
                else:
                    print(f"⚠️  Skipping line {line_num}: Empty context or response")

            except json.JSONDecodeError:
                print(f"⚠️  Skipping line {line_num}: Invalid JSON")
                continue
            except Exception as e:
                print(f"⚠️  Error on line {line_num}: {str(e)}")
                continue

    print(f"✅ Loaded {len(contexts)} valid context-response pairs")
    return contexts, responses


def categorize_mental_health_contexts(contexts):
    """
    Automatically categorize mental health contexts into intent categories
    based on keywords and themes.

    Args:
        contexts (list): List of therapy context strings

    Returns:
        list: List of intent labels for each context
    """
    labels = []

    # Define keyword patterns for different mental health intents
    intent_patterns = {
        'depression': ['depress', 'sad', 'hopeless', 'worthless', 'empty', 'down', 'unmotivated'],
        'anxiety': ['anxious', 'worry', 'nervous', 'panic', 'stress', 'fear', 'overwhelm'],
        'sleep_issues': ['sleep', 'insomnia', 'tired', 'exhausted', 'rest', 'fatigue'],
        'self_esteem': ['worthless', 'confidence', 'self-esteem', 'value', 'myself', 'identity'],
        'relationship': ['relationship', 'partner', 'marriage', 'boyfriend', 'girlfriend', 'divorce'],
        'family': ['family', 'parents', 'mother', 'father', 'siblings', 'children'],
        'suicide': ['suicid', 'kill myself', 'end it', 'die', 'death wish'],
        'trauma': ['trauma', 'abuse', 'ptsd', 'flashback', 'assault'],
        'grief': ['grief', 'loss', 'died', 'death', 'mourning', 'bereave'],
        'anger': ['angry', 'rage', 'furious', 'irritated', 'frustrated'],
        'general_support': []  # Default category
    }

    for context in contexts:
        context_lower = context.lower()
        matched_intent = 'general_support'  # Default

        # Check each intent pattern
        for intent, keywords in intent_patterns.items():
            if any(keyword in context_lower for keyword in keywords):
                matched_intent = intent
                break  # Use first match

        labels.append(matched_intent)

    return labels


# =============================
# DATASET CLASS
# =============================

class TherapyDataset(torch.utils.data.Dataset):
    """
    PyTorch Dataset class for therapy context-response pairs.

    Args:
        encodings (dict): Tokenized inputs from tokenizer
        labels (list): Encoded labels for classification
    """
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        """Get a single item from the dataset."""
        return {
            "input_ids": torch.tensor(self.encodings["input_ids"][idx]),
            "attention_mask": torch.tensor(self.encodings["attention_mask"][idx]),
            "labels": torch.tensor(self.labels[idx]),
        }

    def __len__(self):
        """Return the size of the dataset."""
        return len(self.labels)


# =============================
# MAIN TRAINING PIPELINE
# =============================

def train_therapy_model(data_file_path, output_dir="therapy_model"):
    """
    Complete pipeline to load, clean, and train a therapy response model.

    Args:
        data_file_path (str): Path to the therapy dataset file
        output_dir (str): Directory to save the trained model
    """

    print("\n" + "="*60)
    print("🧠 THERAPY CHATBOT MODEL TRAINING PIPELINE")
    print("="*60 + "\n")

    # -----------------------------
    # STEP 1: LOAD AND CLEAN DATA
    # -----------------------------
    contexts, responses = load_and_clean_therapy_data(data_file_path)

    if len(contexts) == 0:
        print("❌ No valid data found. Exiting.")
        return

    # -----------------------------
    # STEP 2: CATEGORIZE CONTEXTS
    # -----------------------------
    print("\n🏷️  Categorizing contexts into intents...")
    labels = categorize_mental_health_contexts(contexts)

    # Show distribution of intents
    from collections import Counter
    intent_counts = Counter(labels)
    print("\n📊 Intent Distribution:")
    for intent, count in intent_counts.most_common():
        print(f"   {intent}: {count}")

    # -----------------------------
    # STEP 3: ENCODE LABELS
    # -----------------------------
    print("\n🔢 Encoding labels...")
    label_encoder = LabelEncoder()
    encoded_labels = label_encoder.fit_transform(labels)

    # Save label mapping for later use
    label_map = dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
    os.makedirs(output_dir, exist_ok=True)

    with open(f"{output_dir}/label_map.json", "w") as f:
        json.dump(label_map, f, indent=2)
    print(f"✅ Saved label mapping to {output_dir}/label_map.json")

    # Save context-response pairs for retrieval
    training_data = {
        "contexts": contexts,
        "responses": responses,
        "labels": labels
    }
    with open(f"{output_dir}/training_data.json", "w") as f:
        json.dump(training_data, f, indent=2)
    print(f"✅ Saved training data to {output_dir}/training_data.json")

    # -----------------------------
    # STEP 4: SPLIT DATA
    # -----------------------------
    print("\n✂️  Splitting data into train/validation sets...")
    train_texts, val_texts, train_labels, val_labels = train_test_split(
        contexts,
        encoded_labels,
        test_size=0.2,
        random_state=42,
        stratify=encoded_labels
    )
    print(f"   Training samples: {len(train_texts)}")
    print(f"   Validation samples: {len(val_texts)}")

    # -----------------------------
    # STEP 5: TOKENIZATION
    # -----------------------------
    print("\n🔤 Loading tokenizer and tokenizing data...")
    tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

    train_encodings = tokenizer(
        train_texts,
        truncation=True,
        padding=True,
        max_length=256  # Longer for therapy contexts
    )
    val_encodings = tokenizer(
        val_texts,
        truncation=True,
        padding=True,
        max_length=256
    )
    print("✅ Tokenization complete")

    # -----------------------------
    # STEP 6: CREATE DATASETS
    # -----------------------------
    print("\n📦 Creating PyTorch datasets...")
    train_dataset = TherapyDataset(train_encodings, train_labels)
    val_dataset = TherapyDataset(val_encodings, val_labels)

    # -----------------------------
    # STEP 7: LOAD MODEL
    # -----------------------------
    print("\n🤖 Loading DistilBERT model...")
    model = DistilBertForSequenceClassification.from_pretrained(
        "distilbert-base-uncased",
        num_labels=len(label_map),
    )
    print(f"✅ Model loaded with {len(label_map)} output classes")

    # -----------------------------
    # STEP 8: CONFIGURE TRAINING
    # -----------------------------
    print("\n⚙️  Configuring training parameters...")
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=10,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        learning_rate=2e-5,
        weight_decay=0.01,
        warmup_steps=100,
        logging_dir=f"{output_dir}/logs",
        logging_steps=10,
        save_strategy="epoch",
        eval_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        report_to="none",
    )

    # -----------------------------
    # STEP 9: TRAIN MODEL
    # -----------------------------
    print("\n🚀 Starting training...\n")
    print("="*60)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
    )

    trainer.train()

    # -----------------------------
    # STEP 10: SAVE MODEL
    # -----------------------------
    print("\n💾 Saving trained model...")
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)

    # Final evaluation
    final_metrics = trainer.evaluate()
    print("\n" + "="*60)
    print("✅ TRAINING COMPLETE!")
    print("="*60)
    print(f"📊 Final Validation Loss: {final_metrics['eval_loss']:.4f}")
    print(f"📁 Model saved to: {output_dir}/")
    print("\nFiles created:")
    print(f"   - {output_dir}/pytorch_model.bin (model weights)")
    print(f"   - {output_dir}/config.json (model config)")
    print(f"   - {output_dir}/label_map.json (intent labels)")
    print(f"   - {output_dir}/training_data.json (for response retrieval)")
    print("="*60 + "\n")


# =============================
# INFERENCE FUNCTION
# =============================

def predict_therapy_response(text, model_dir="therapy_model"):
    """
    Predict intent and retrieve appropriate response for user input.

    Args:
        text (str): User's input message
        model_dir (str): Directory containing the trained model

    Returns:
        tuple: (intent, response)
    """
    import random

    # Load model and tokenizer
    model = DistilBertForSequenceClassification.from_pretrained(model_dir)
    tokenizer = DistilBertTokenizerFast.from_pretrained(model_dir)

    # Load label mapping
    with open(f"{model_dir}/label_map.json", "r") as f:
        label_map = json.load(f)

    # Load training data for response retrieval
    with open(f"{model_dir}/training_data.json", "r") as f:
        training_data = json.load(f)

    # Predict
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=256)

    with torch.no_grad():
        outputs = model(**inputs)

    prediction = torch.argmax(outputs.logits, dim=1).item()

    # Get intent
    intent = [k for k, v in label_map.items() if v == prediction][0]

    # Find matching responses
    matching_responses = [
        training_data["responses"][i]
        for i, label in enumerate(training_data["labels"])
        if label == intent
    ]

    # Return random response from matching category
    response = random.choice(matching_responses) if matching_responses else "I'm here to listen and support you."

    return intent, response


# =============================
# EXAMPLE USAGE
# =============================

if __name__ == "__main__":
    # Train the model
    train_therapy_model("therapy_data.json", output_dir="therapy_model")

    # Example inference after training
    print("\n" + "="*60)
    print("🧪 TESTING INFERENCE")
    print("="*60 + "\n")

    test_inputs = [
        "I feel so worthless and can't sleep at night",
        "I'm constantly worried about everything",
        "I lost my loved one recently"
    ]

    for test_input in test_inputs:
        intent, response = predict_therapy_response(test_input)
        print(f"Input: {test_input}")
        print(f"Intent: {intent}")
        print(f"Response: {response[:100]}...")
        print("-" * 60 + "\n")

import os
import json

print("🔍 Checking therapy_model directory...\n")

if os.path.exists("therapy_model"):
    files = os.listdir("therapy_model")

    print(f"📁 Found {len(files)} files in therapy_model/")
    print("\nFiles present:")
    for f in sorted(files):
        size = os.path.getsize(f"therapy_model/{f}") / (1024*1024)  # Size in MB
        print(f"   ✓ {f} ({size:.2f} MB)")

    # Check for key model files
    print("\n📊 Status Check:")

    has_model = "pytorch_model.bin" in files or "model.safetensors" in files
    has_config = "config.json" in files
    has_tokenizer = "tokenizer.json" in files or "vocab.txt" in files
    has_label_map = "label_map.json" in files
    has_training_data = "training_data.json" in files

    print(f"   Model weights: {'✅' if has_model else '❌'}")
    print(f"   Config: {'✅' if has_config else '❌'}")
    print(f"   Tokenizer: {'✅' if has_tokenizer else '❌'}")
    print(f"   Label map: {'✅' if has_label_map else '❌'}")
    print(f"   Training data: {'✅' if has_training_data else '❌'}")

    if has_model and has_config and has_tokenizer:
        print("\n🎉 YOUR MODEL IS COMPLETE AND READY TO USE!")
        print("Even though you were at epoch 9/10, your model is fully trained and working!")
    else:
        print("\n❌ Model is incomplete. Need to retrain.")

else:
    print("❌ therapy_model directory doesn't exist!")



print("🧪 Testing your trained model...\n")

from transformers import DistilBertForSequenceClassification, DistilBertTokenizerFast
import torch
import json

try:
    # Load model
    model = DistilBertForSequenceClassification.from_pretrained("therapy_model")
    tokenizer = DistilBertTokenizerFast.from_pretrained("therapy_model")

    # Load label map
    with open("therapy_model/label_map.json", "r") as f:
        label_map = json.load(f)

    reverse_label_map = {v: k for k, v in label_map.items()}

    print("✅ Model loaded successfully!\n")

    # Test predictions
    test_cases = [
        "I feel worthless and can't sleep",
        "My relationship is falling apart",
        "I'm constantly anxious about everything",
        "I lost my loved one recently"
    ]

    print("🔮 Test Predictions:\n")

    for test_text in test_cases:
        inputs = tokenizer(test_text, return_tensors="pt", truncation=True, padding=True)

        with torch.no_grad():
            outputs = model(**inputs)

        # Get prediction
        probs = torch.softmax(outputs.logits, dim=1)
        prediction = torch.argmax(probs).item()
        confidence = probs[0][prediction].item()

        intent = reverse_label_map[prediction]

        print(f"Input: \"{test_text}\"")
        print(f"   → Intent: {intent}")
        print(f"   → Confidence: {confidence*100:.1f}%\n")

    print("="*60)
    print("✅ YOUR MODEL IS WORKING PERFECTLY!")
    print("="*60)
    print("\n📋 Next Steps:")
    print("   1. Upload to Hugging Face")
    print("   2. Generate response database")
    print("   3. Deploy to Next.js\n")

except Exception as e:
    print(f"❌ Error loading model: {e}")
    print("\nYou need to retrain from scratch.")

"""
FAST THERAPY MODEL RETRAINING - FIXED
======================================
"""

import json
import torch
import os
import numpy as np  # Add this import
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
import time

# Disable unnecessary outputs
os.environ["WANDB_DISABLED"] = "true"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
warnings.filterwarnings("ignore")

start_time = time.time()

print("\n" + "="*70)
print("🚀 FAST THERAPY MODEL RETRAINING")
print("="*70 + "\n")

# =============================================
# STEP 1: LOAD DATA
# =============================================
print("📂 Loading previously processed training data...")

with open("therapy_model/training_data.json", "r") as f:
    training_data = json.load(f)

contexts = training_data["contexts"]
labels_text = training_data["labels"]

print(f"✅ Loaded {len(contexts)} contexts")

with open("therapy_model/label_map.json", "r") as f:
    label_map = json.load(f)

print(f"✅ Loaded {len(label_map)} intent categories")

# =============================================
# STEP 2: ENCODE LABELS (FIXED)
# =============================================
print("\n🔢 Encoding labels...")

label_encoder = LabelEncoder()
# FIX: Fit the encoder properly with numpy array
label_encoder.fit(np.array(sorted(label_map.keys())))
labels = label_encoder.transform(labels_text)

print(f"✅ Labels encoded")

# =============================================
# STEP 3: SPLIT DATA
# =============================================
print("\n✂️  Splitting data...")
train_texts, val_texts, train_labels, val_labels = train_test_split(
    contexts,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

print(f"   Training: {len(train_texts)} samples")
print(f"   Validation: {len(val_texts)} samples")

# =============================================
# STEP 4: TOKENIZATION
# =============================================
print("\n🔤 Tokenizing data...")

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)

print("✅ Tokenization complete")

# =============================================
# STEP 5: CREATE DATASETS
# =============================================
print("\n📦 Creating PyTorch datasets...")

class TherapyDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.encodings["input_ids"][idx]),
            "attention_mask": torch.tensor(self.encodings["attention_mask"][idx]),
            "labels": torch.tensor(self.labels[idx]),
        }

    def __len__(self):
        return len(self.labels)

train_dataset = TherapyDataset(train_encodings, train_labels)
val_dataset = TherapyDataset(val_encodings, val_labels)

print("✅ Datasets created")

# =============================================
# STEP 6: LOAD MODEL
# =============================================
print("\n🤖 Loading DistilBERT model...")

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label_map),
)

print(f"✅ Model initialized with {len(label_map)} output classes")

# =============================================
# STEP 7: TRAINING CONFIGURATION
# =============================================
print("\n⚙️  Configuring FAST training parameters...")

training_args = TrainingArguments(
    output_dir="therapy_model_v2",
    num_train_epochs=6,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=3e-5,
    weight_decay=0.01,
    warmup_steps=50,
    logging_steps=50,
    logging_dir="therapy_model_v2/logs",
    save_strategy="epoch",
    save_total_limit=1,
    eval_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    dataloader_num_workers=0,
    report_to="none",
    disable_tqdm=False,
)

print("✅ Configuration complete")

# =============================================
# STEP 8: CREATE TRAINER
# =============================================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

# =============================================
# STEP 9: TRAIN
# =============================================
print("\n" + "="*70)
print("🚀 STARTING TRAINING")
print("="*70)
print("\n💡 Expected time: 45-60 minutes on CPU\n")

try:
    trainer.train()

    # =============================================
    # STEP 10: SAVE
    # =============================================
    print("\n💾 Saving trained model...")

    model.save_pretrained("therapy_model_v2")
    tokenizer.save_pretrained("therapy_model_v2")

    # Copy metadata
    import shutil
    shutil.copy("therapy_model/label_map.json", "therapy_model_v2/label_map.json")
    shutil.copy("therapy_model/training_data.json", "therapy_model_v2/training_data.json")

    # =============================================
    # STEP 11: EVALUATE
    # =============================================
    print("\n📊 Final evaluation...")
    final_metrics = trainer.evaluate()

    elapsed_time = time.time() - start_time

    print("\n" + "="*70)
    print("✅ TRAINING COMPLETE!")
    print("="*70)
    print(f"⏱️  Total time: {elapsed_time/60:.1f} minutes")
    print(f"📊 Final validation loss: {final_metrics['eval_loss']:.4f}")
    print(f"📁 Model saved to: therapy_model_v2/")
    print("="*70)

    # =============================================
    # STEP 12: TEST
    # =============================================
    print("\n🧪 Testing the trained model...\n")

    test_cases = [
        "I feel worthless and can't sleep",
        "My relationship is falling apart",
        "I'm constantly worried",
        "I lost someone I love"
    ]

    reverse_label_map = {v: k for k, v in label_map.items()}

    for test_text in test_cases:
        inputs = tokenizer(test_text, return_tensors="pt", truncation=True, padding=True)

        with torch.no_grad():
            outputs = model(**inputs)

        probs = torch.softmax(outputs.logits, dim=1)
        prediction = torch.argmax(probs).item()
        confidence = probs[0][prediction].item()

        intent = reverse_label_map[prediction]

        print(f"Input: \"{test_text}\"")
        print(f"   → {intent} ({confidence*100:.1f}% confident)\n")

    print("="*70)
    print("🎉 MODEL READY FOR DEPLOYMENT!")
    print("="*70)

except KeyboardInterrupt:
    print("\n⚠️  Training interrupted!")

except Exception as e:
    print(f"\n❌ Error: {e}")
    import traceback
    traceback.print_exc()

# In Google Colab, run this to download your trained model

import shutil

# Compress the model folder
print("📦 Compressing model...")
shutil.make_archive('therapy_model_v2', 'zip', 'therapy_model_v2')

print("✅ Model compressed to therapy_model_v2.zip")

# Download the zip file
from google.colab import files
files.download('therapy_model_v2.zip')

print("⬇️ Download started! Check your browser downloads.")